# Generated by Django 5.2.17 on 2026-10-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheetentry',
            options={'ordering': ['-date', '-start_time', '-id']},
        ),
    ]
